litellm_settings:
  drop_params: True

model_list:
  - model_name: gemini-1.5-flash-001
    litellm_params:
      model: vertex_ai/gemini-1.5-flash-001
      vertex_project: os.environ/PROJECT_ID
      vertex_location: "asia-east2"
  - model_name: gemini-1.5-pro-001
    litellm_params:
      model: vertex_ai/gemini-1.5-pro-001
      vertex_project: os.environ/PROJECT_ID
      vertex_location: "asia-east2"
  - model_name: text-multilingual-embedding-002
    litellm_params:
      model: vertex_ai/text-multilingual-embedding-002
      vertex_project: os.environ/PROJECT_ID
      vertex_location: "asia-east2"
